spring:
  application:
    name: delivery

  zipkin:
    base-url: ${ZIPKIN_URL}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

    region:
      auto: false
      static: ap-northeast-2

    stack:
      auto: false

post.queue.name: ${POST_QUEUE_NAME}
delivery.queue.name: ${DELIVERY_QUEUE_NAME}
