app:
  queue:
    name: ${CONSUME_QUEUE_NAME}
    name-2: ${PUBLISH_QUEUE_NAME}

spring:
  application:
    name: delivery

  zipkin:
    base-url: ${ZIPKIN_URL}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

    region:
      auto: false
      static: ap-northeast-2

    stack:
      auto: false

